// pages/index.tsx

import { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { Button, Container } from "reactstrap"
import Header from "@/components/Header"
import CartTable from "@/components/CartTable"
import CartTotal from "@/components/CartTotal"

const Cart: NextPage = () => {
    return (
        <>
            <Head>
                <title>Cart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main >
                <Container className="py-5">
                    <h1 className="my-5">
                        Carrinho
                    </h1>
                    <CartTable />
                    <CartTotal />
                </Container>
            </main>
        </>
    )
}

export default Cart;